version: '3.8'

services:
    meetup:
        image: jitsi/web:stable
        restart: unless-stopped
        volumes:
            - ./config/web:/config
        environment:
            - ENABLE_LETSENCRYPT=0
            - DISABLE_HTTPS=0
            - PUBLIC_URL=https://meet.meetup.mathe-host.de
        networks:
            - meet.jitsi
            - coolify
        depends_on:
            - prosody
            - jicofo
            - jvb

    prosody:
        image: jitsi/prosody:stable
        restart: unless-stopped
        volumes:
            - ./config/prosody:/config
        environment:
            - AUTH_TYPE=internal
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=supersecret
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=anothersecret
        ports:
            - "5222:5222"
            - "5347:5347"
            - "5280:5280"
        networks:
            - meet.jitsi

    jicofo:
        image: jitsi/jicofo:stable
        restart: unless-stopped
        volumes:
            - ./config/jicofo:/config
        environment:
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=supersecret
            - XMPP_DOMAIN=meet.meetup.mathe-server.de
            - XMPP_AUTH_DOMAIN=auth.meetup.mathe-server.de
            - XMPP_SERVER=prosody
        networks:
            - meet.jitsi
        depends_on:
            - prosody

    jvb:
        image: jitsi/jvb:stable
        restart: unless-stopped
        volumes:
            - ./config/jvb:/config
        ports:
            - "10000:10000/udp"
        environment:
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=anothersecret
            - XMPP_AUTH_DOMAIN=auth.meetup.mathe-host.de
            - XMPP_SERVER=prosody
            - JVB_PORT=10000
            - JVB_PORT_MAPPING=10000
            - JVB_ADVERTISE_IPS=168.119.109.202
        networks:
            - meet.jitsi
        depends_on:
            - prosody


networks:
    meet.jitsi:
    coolify:
        external: true
